"""empty message

Revision ID: 29adadf21565
Revises: 
Create Date: 2020-05-26 15:51:47.159345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29adadf21565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image')
    # ### end Alembic commands ###
